import os
import typer
import questionary
from pathlib import Path
from documentor.core.config import Config, DocItem
from documentor.cli.context import ctx
from documentor.cli.utils import handle_cancel, should_use_agent, run_generation
from documentor.utils.style import load_style_template, get_style_templates
from documentor.llm.chains.agent import agent_generate_plan
from documentor.llm.chains import generate_plan

app = typer.Typer(help="Setup commands for Documentor.")

@app.command(name="init")
def init():
    """Interactive setup to initialize documentor configuration."""
    ctx.console.print("[blue]Welcome to Documentor![/blue]")

    if ctx.config_manager.config_exists() or ctx.state_manager.statefile_exists():
        overwrite = handle_cancel(
            questionary.confirm(
                "It seems this project was already initialized. Do you want to clear the existing configuration and start over?",
                default=False,
            ).ask()
        )
        if not overwrite:
            ctx.console.print(
                "[yellow]Initialization cancelled to prevent overwriting existing config.[/yellow]"
            )
            raise typer.Exit(0)
        else:
            ctx.config_manager.clear_config()
            ctx.state_manager.clear_statefile()
            ctx.console.print(
                "[green]Existing configuration cleared. Starting fresh initialization.[/green]"
            )

    config_data = {}

    # choose doc directory
    default_output = handle_cancel(
        questionary.confirm(
            "Use default output settings (docs directory, no footer)?", default=True
        ).ask()
    )
    if not default_output:
        config_data["docs_dir"] = handle_cancel(
            questionary.text("Enter output directory for docs:", default="docs").ask()
        )
        config_data["include_footer"] = handle_cancel(
            questionary.confirm(
                "Include 'Generated by Documentor' footer in markdown?", default=False
            ).ask()
        )

    # tracking options
    config_data["use_git"] = handle_cancel(
        questionary.confirm(
            "Use git-based tracking for incremental updates?", default=True
        ).ask()
    )

    # style md setup
    config_data["style_md_path"] = handle_cancel(
        questionary.text(
            "Enter the path to use for style.md (leave empty to skip):",
            default=f"{config_data.get('docs_dir', 'docs')}/style.md",
        ).ask()
    ).strip()

    # llm setup
    default_model = handle_cancel(
        questionary.confirm(
            "Use default model (Google Vertex AI with gemini-3.1-pro)?", default=True
        ).ask()
    )
    if not default_model:
        config_data["provider"] = handle_cancel(
            questionary.select(
                "Choose LLM provider:",
                choices=["vertexai", "openai", "ollama"],
                default="vertexai",
            ).ask()
        )
        config_data["model"] = handle_cancel(
            questionary.text(
                "Enter model name:", default="gemini-3.1-pro-preview"
            ).ask()
        )

    # file ignores setup
    default_ignore = handle_cancel(
        questionary.confirm(
            "Use default ignore setup (ignore common dirs like .git, venv, and files > 100KB)?",
            default=True,
        ).ask()
    )
    if not default_ignore:
        size_str = handle_cancel(
            questionary.text("Ignore files above size (KB):", default="100").ask()
        )
        config_data["ignore_above_size_kb"] = (
            int(size_str) if size_str.isdigit() else 100
        )
        ignore_patterns_str = handle_cancel(
            questionary.text(
                "Enter ignore patterns (comma-separated):",
                default=".git, __pycache__, venv, .venv, env, node_modules, .env, *.pyc, *.pyo",
            ).ask()
        )
        config_data["ignore_patterns"] = [
            p.strip() for p in ignore_patterns_str.split(",")
        ]

    # agent setup
    agent_choice = handle_cancel(
        questionary.select(
            "Use agent-mode (An agent will dynamcially handle your files instead of full-project context)?",
            choices=[
                questionary.Choice("Enable agent-mode always", value="always"),
                questionary.Choice(
                    "Enable agent-mode if project context exceeds a threshold",
                    value="threshold",
                ),
                questionary.Choice("Disable agent-mode", value="never"),
            ],
        ).ask()
    )

    if agent_choice == "always":
        config_data["agent_threshold_kb"] = 0
    elif agent_choice == "threshold":
        threshold_str = handle_cancel(
            questionary.text(
                "Threshold in KB for automatic agent mode:", default="1000"
            ).ask()
        )
        config_data["agent_threshold_kb"] = (
            int(threshold_str) if threshold_str.isdigit() else 1000
        )
    else:
        config_data["agent_threshold_kb"] = -1

    config = Config(**config_data)
    ctx.config_manager.save_config(config)

    # Re-initialize context with the new config
    ctx.reload()

    ctx.console.print("[green]Created documentor.yaml successfully![/green]")

    # style.md setup
    if ctx.config.style_md_path:
        create_style = handle_cancel(
            questionary.confirm(
                f"Do you want to create and initialize {ctx.config.style_md_path}?",
                default=True,
            ).ask()
        )
        if create_style:
            style_path = ctx.config.style_md_path or os.path.join(
                ctx.config.docs_dir or "docs", "style.md"
            )
            os.makedirs(os.path.dirname(style_path) or ".", exist_ok=True)

            # select a template
            choices = [f.replace(".md", "") for f in get_style_templates()] + ["empty"]
            selected_template = handle_cancel(
                questionary.select(
                    "Choose a style template to initialize with:",
                    choices=choices,
                    default="empty",
                ).ask()
            )

            if not os.path.exists(style_path):
                if selected_template == "empty":
                    content = "# Documentation Style Guide\n\nAdd your formatting and style instructions here. These will be used by Documentor when generating your docs.\n"
                else:
                    content = load_style_template(selected_template)

                with open(style_path, "w", encoding="utf-8") as f:
                    f.write(content)
                ctx.console.print(
                    f"[green]Created {style_path} using {selected_template} template![/green]"
                )
            else:
                ctx.console.print(
                    f"[yellow]{style_path} already exists. Skipping initialization.[/yellow]"
                )

    # plan setup (documentor plan)
    ctx.console.print("[blue]Analyzing project context to generate plan...[/blue]")
    existing_docs = []

    if should_use_agent(ctx.config, ctx.parser):
        suggested_files = agent_generate_plan(ctx.config, existing_docs)
    else:
        context = ctx.parser.extract_context()
        suggested_files = generate_plan(context, ctx.config, existing_docs)

    ctx.console.print(
        f"[green]AI suggested {len(suggested_files)} files based on project context.[/green]"
    )

    if suggested_files:
        for doc in suggested_files:
            ctx.state_manager.upsert_doc(
                filepath=Path(os.path.join(ctx.config.docs_dir, doc.filename)),
                description=doc.description,
            )

    ctx.console.print(
        "[blue]Initialization complete! Run `documentor generate` to generate your documentation.[/blue]"
    )


@app.command(name="add-readme")
def add_readme(
    once: bool = typer.Option(
        False,
        "--once",
        help="Delete documentor state files after generating the README",
    ),
):
    """Quickly add an autogenerated readme file to your repo"""
    ctx.console.print("[blue]Adding autogenerated README.md...[/blue]")

    if ctx.config_manager.config_exists() or ctx.state_manager.statefile_exists():
        ctx.console.print(
            "[red]Error: Documentor configuration or lockfile already exists. This command should be used on a fresh repo.[/red]"
        )
        raise typer.Exit(1)

    style_path = "style.md"
    style_existed = os.path.exists(style_path)
    if not style_existed:
        content = load_style_template("basic")
        with open(style_path, "w", encoding="utf-8") as f:
            f.write(content)
        ctx.console.print(f"[green]Created {style_path} using basic template.[/green]")

    config_data = {
        "docs_dir": ".",
        "style_md_path": style_path,
        "use_git": True,
        "provider": "vertexai",
        "model": "gemini-3.1-pro-preview",
        "ignore_above_size_kb": 100,
        "ignore_patterns": [
            ".git",
            "__pycache__",
            "venv",
            ".venv",
            "env",
            "node_modules",
            ".env",
            "*.pyc",
            "*.pyo",
        ],
        "agent_threshold_kb": 1000,
        "include_footer": False,
    }

    config = Config(**config_data)
    ctx.config_manager.save_config(config)

    ctx.reload()

    readme_path = "README.md"
    doc_item = DocItem(filename=readme_path, description="Project README file")
    
    ctx.state_manager.upsert_doc(
        filepath=Path(readme_path), description=doc_item.description
    )

    run_generation([doc_item])

    if once:
        ctx.console.print("[blue]Cleaning up documentor state files (--once)...[/blue]")
        if ctx.config_manager.config_exists():
            os.remove(ctx.config_manager.config_file)
        ctx.state_manager.clear_statefile()
        if not style_existed and os.path.exists(style_path):
            os.remove(style_path)
        ctx.console.print("[green]Cleanup complete! Left only the README.md[/green]")


@app.command(name="destroy")
def destroy(
    with_files: bool = typer.Option(
        False, "--with-files", help="Also delete all tracked documentation files"
    ),
    force: bool = typer.Option(
        False, "-f", "--force", help="Skip confirmation prompt"
    ),
):
    """Removes the documentor config and lockfile."""
    ctx.console.print("[blue]Destroying Documentor configuration...[/blue]")

    if not force:
        msg = "Are you sure you want to destroy Documentor configuration and lockfile?"
        if with_files:
            msg += " THIS WILL ALSO DELETE ALL TRACKED DOCUMENTATION FILES."
        msg += " This cannot be undone."

        confirm = questionary.confirm(msg, default=False).ask()
        if not confirm:
            ctx.console.print("[yellow]Destruction cancelled.[/yellow]")
            raise typer.Exit(0)

    if with_files:
        ctx.console.print("[blue]Deleting tracked documentation files...[/blue]")
        for ds in ctx.state_manager.state.managed_docs:
            if os.path.exists(ds.filepath):
                try:
                    os.remove(ds.filepath)
                    ctx.console.print(f"[green]Deleted {ds.filepath}[/green]")
                except Exception as e:
                    ctx.console.print(f"[red]Error deleting {ds.filepath}: {e}[/red]")

    if ctx.config_manager.config_exists():
        os.remove(ctx.config_manager.config_file)
        ctx.console.print("[green]Deleted documentor.yaml[/green]")
    else:
        ctx.console.print("[yellow]documentor.yaml not found.[/yellow]")

    if ctx.state_manager.statefile_exists():
        ctx.state_manager.clear_statefile()
        ctx.console.print("[green]Deleted documentor-lock.yaml[/green]")
    else:
        ctx.console.print("[yellow]documentor-lock.yaml not found.[/yellow]")

    ctx.console.print("[green]Documentor successfully destroyed for this project.[/green]")
