import os
from typing import Optional
import typer
from rich.console import Console
import questionary
from documentor.core.config import Config, ConfigManager
from documentor.core.state import StateManager
from documentor.llm.chains import generate_docs, edit_doc, expand_doc, sync_doc, generate_plan, infer_doc_info
from documentor.core.parser import Parser
from documentor.core.writer import Writer
from documentor.utils.style import load_style_template, get_style_templates

__version__ = "1.0.0"

app = typer.Typer(help="Documentor: A CLI tool for automatic documentation generation and management")
console = Console()

def version_callback(value: bool):
    if value:
        console.print(f"Documentor version: {__version__}")
        raise typer.Exit()

@app.callback()
def main(
    version: Optional[bool] = typer.Option(
        None,
        "--version",
        callback=version_callback,
        is_eager=True,
        help="Show the application's version and exit.",
    )
):
    pass

def handle_cancel(val):
    if val is None:
        console.print("[red]Initialization cancelled by user.[/red]")
        raise typer.Exit(1)
    return val

@app.command()
def plan():
    """Analyzes the project context and suggests a list of documentation files to be managed."""
    console.print("[blue]Planning documentation suite...[/blue]")
    config_manager = ConfigManager()
    config = config_manager.load_config()

    parser = Parser(config)
    context = parser.extract_context()

    suggested_files = generate_plan(context, config)

    if not suggested_files:
        console.print("[yellow]No new documentation files suggested.[/yellow]")
        return

    console.print("\n[blue]Suggested Documentation Files:[/blue]")
    for doc in suggested_files:
        console.print(f"- [cyan]{doc.filename}[/cyan] ({doc.type}): {doc.description}")

    if config.required_files:
        action = handle_cancel(questionary.select(
            "You already have required files in your config. What would you like to do?",
            choices=[
                questionary.Choice("Merge (add new suggestions to existing list)", value="merge"),
                questionary.Choice("Overwrite (replace existing list with suggestions)", value="overwrite"),
                questionary.Choice("Cancel", value="cancel")
            ]
        ).ask())

        if action == "cancel":
            console.print("[yellow]Planning cancelled.[/yellow]")
            return
        elif action == "merge":
            existing_filenames = {f.filename.lower() for f in config.required_files}
            for doc in suggested_files:
                if doc.filename.lower() not in existing_filenames:
                    config.required_files.append(doc)
        else:
            config.required_files = suggested_files
    else:
        confirm = handle_cancel(questionary.confirm("Do you want to add these suggestions to your required files?", default=True).ask())
        if confirm:
            config.required_files = suggested_files
        else:
            console.print("[yellow]Planning cancelled.[/yellow]")
            return

    config_manager.save_config(config)
    console.print("[green]Updated documentor.yaml with the new documentation plan![/green]")

@app.command()
def init():
    """Interactive setup to initialize documentor configuration."""
    console.print("[blue]Welcome to Documentor initialization![/blue]")

    config_manager = ConfigManager()
    state_manager = StateManager(config_manager.load_config())
    if config_manager.config_exists() or state_manager.statefile_exists():
        overwrite = handle_cancel(questionary.confirm("It seems this project was already initialized. Do you want to clear the existing configuration and start over?", default=False).ask())
        if not overwrite:
            console.print("[yellow]Initialization cancelled to prevent overwriting existing config.[/yellow]")
            raise typer.Exit(0)
        else:
            config_manager.clear_config()
            state_manager.clear_statefile()
            console.print("[green]Existing configuration cleared. Starting fresh initialization.[/green]")

    config_data = {}

    # choose doc directory
    default_output = handle_cancel(questionary.confirm("Use default output settings (docs directory, no footer)?", default=True).ask())
    if not default_output:
        config_data["docs_dir"] = handle_cancel(questionary.text("Enter output directory for docs:", default="docs").ask())
        config_data["include_footer"] = handle_cancel(questionary.confirm("Include 'Generated by Documentor' footer in markdown?", default=False).ask())

    # tracking options
    config_data["use_git"] = handle_cancel(questionary.confirm("Use git-based tracking for incremental updates?", default=True).ask())

    # required files setup
    method = handle_cancel(questionary.select(
        "How would you like to specify the required doc files?",
        choices=[
            questionary.Choice("Manual (enter each file)", value="manual"),
            questionary.Choice("Auto-generate (AI-assisted plan)", value="auto")
        ]
    ).ask())

    required_files = []
    if method == "manual":
        while True:
            filename = handle_cancel(questionary.text("Enter required filename (or empty to finish):", default="").ask())
            if not filename:
                break
            filename = filename if filename.lower().endswith(".md") else f"{filename}.md"
            file_type = handle_cancel(questionary.text(f"Enter document type for {filename}:", default="Overview").ask())
            file_description = handle_cancel(questionary.text(f"Enter a short description for {filename}:", default="").ask())
            required_files.append({"filename": filename, "type": file_type, "description": file_description})
    else:
        console.print("[blue]Analyzing project context to generate plan...[/blue]")
        parser = Parser(Config(**config_data))
        context = parser.extract_context()
        required_files = generate_plan(context, Config(**config_data))
        console.print(f"[green]AI suggested {len(required_files)} files based on project context.[/green]")

    if required_files:
        config_data["required_files"] = required_files

    required_files_only = handle_cancel(questionary.confirm("Only use the required files (won't generate other docs)?", default=True).ask())
    if required_files_only:
        config_data["required_only"] = required_files_only

    # style md setup
    config_data["use_style_md"] = handle_cancel(questionary.confirm("Use a style.md file for formatting instructions?", default=True).ask())
    if config_data["use_style_md"]:
        config_data["style_md_path"] = handle_cancel(questionary.text("Enter the path to use for style.md:", default=f"{config_data.get('docs_dir', 'docs')}/style.md").ask())

    # llm setup
    default_model = handle_cancel(questionary.confirm("Use default model (Google Vertex AI with gemini-3.1-pro)?", default=True).ask())
    if not default_model:
        config_data["provider"] = handle_cancel(questionary.select(
            "Choose LLM provider:",
            choices=["vertexai", "openai", "ollama"],
            default="vertexai"
        ).ask())
        config_data["model"] = handle_cancel(questionary.text("Enter model name:", default="gemini-3.1-pro-preview").ask())

    # file ignores setup
    default_ignore = handle_cancel(questionary.confirm("Use default ignore setup (ignore common dirs like .git, venv, and files > 100KB)?", default=True).ask())
    if not default_ignore:
        size_str = handle_cancel(questionary.text("Ignore files above size (KB):", default="100").ask())
        config_data["ignore_above_size_kb"] = int(size_str) if size_str.isdigit() else 100
        ignore_patterns_str = handle_cancel(questionary.text("Enter ignore patterns (comma-separated):", default=".git, __pycache__, venv, .venv, env, node_modules, .env, *.pyc, *.pyo").ask())
        config_data["ignore_patterns"] = [p.strip() for p in ignore_patterns_str.split(",")]

    config = Config(**config_data)
    config_manager.save_config(config)

    console.print("[green]Created documentor.yaml successfully![/green]")

    # style.md setup
    # TODO style md generation with questionnaire
    if config.use_style_md:
        create_style = handle_cancel(questionary.confirm(f"Do you want to create and initialize {config.style_md_path}?", default=True).ask())
        if create_style:
            style_path = config.style_md_path or os.path.join(config.docs_dir or "docs", "style.md")
            os.makedirs(os.path.dirname(style_path) or ".", exist_ok=True)

            # select a template
            choices = [f.replace(".md", "") for f in get_style_templates()] + ["empty"]
            selected_template = handle_cancel(questionary.select(
                "Choose a style template to initialize with:",
                choices=choices,
                default="empty"
            ).ask())

            if not os.path.exists(style_path):
                if selected_template == "empty":
                    content = "# Documentation Style Guide\n\nAdd your formatting and style instructions here. These will be used by Documentor when generating your docs.\n"
                else:
                    content = load_style_template(selected_template)

                with open(style_path, "w", encoding="utf-8") as f:
                    f.write(content)
                console.print(f"[green]Created {style_path} using {selected_template} template![/green]")
            else:
                console.print(f"[yellow]{style_path} already exists. Skipping initialization.[/yellow]")

    console.print("[blue]Initialization complete! Run `documentor generate` to generate your documentation.[/blue]")

@app.command()
def generate(force_regenerate: bool = typer.Option(False, "--force", "-f", help="Force regeneration of all documentation, ignoring tracking state")):
    """On-demand generation based on documentor.yaml."""
    config_manager = ConfigManager()
    config = config_manager.load_config()

    if not config.required_files:
        console.print("[yellow]No documentation files defined in documentor.yaml.[/yellow]")
        console.print("[blue]Try running `documentor plan` to automatically suggest documentation files.[/blue]")
        return

    parser = Parser(config)
    context = parser.extract_context()
    state_manager = StateManager(config)

    docs_to_generate = []
    if force_regenerate:
        docs_to_generate = config.required_files
        console.print("[blue]Force regenerating all documentation...[/blue]")
    else:
        stale_docs = {ds.doc_path for ds in state_manager.get_stale_docs()}
        for doc in config.required_files:
            doc_path = os.path.join(config.docs_dir, doc.filename)
            if not os.path.exists(doc_path) or doc_path in stale_docs:
                docs_to_generate.append(doc)

    if not docs_to_generate:
        console.print("[green]All documentation is up to date![/green]")
        return

    console.print(f"[blue]Generating {len(docs_to_generate)} documentation files...[/blue]")
    generated_files = generate_docs(context, config, docs_to_generate)

    for file_path in generated_files:
        state_manager.update_doc_state(doc_path=file_path)

    console.print("[green]Generation complete![/green]")

@app.command()
def edit(target_file: str):
    """Iterates on an existing markdown document using AI based on user comments."""
    console.print(f"[blue]Editing {target_file}...[/blue]")
    config_manager = ConfigManager()
    config = config_manager.load_config()

    if not os.path.exists(target_file):
        console.print(f"[red]Error: {target_file} not found.[/red]")
        raise typer.Exit(1)

    comments = typer.prompt("Please enter your comments for the AI")

    with open(target_file, "r", encoding="utf-8") as f:
        content = f.read()

    new_content = edit_doc(content, comments, config)

    writer = Writer(config)
    final_path = writer.write(target_file, new_content)

    state_manager = StateManager(config)
    state_manager.update_doc_state(doc_path=final_path)

    console.print(f"[green]Successfully edited {target_file}![/green]")

@app.command()
def expand(target_file: str):
    """Turns scrappy bullet points into a coherent, well-formatted document using AI inference for metadata."""
    console.print(f"[blue]Expanding {target_file}...[/blue]")
    config_manager = ConfigManager()
    config = config_manager.load_config()

    if not os.path.exists(target_file):
        console.print(f"[red]Error: {target_file} not found.[/red]")
        raise typer.Exit(1)

    parser = Parser(config)
    context = parser.extract_context()

    filename = os.path.basename(target_file)
    doc_info = infer_doc_info(filename, context, config)

    console.print(f"[blue]Inferred Type: {doc_info.type}[/blue]")
    console.print(f"[blue]Inferred Description: {doc_info.description}[/blue]")

    with open(target_file, "r", encoding="utf-8") as f:
        content = f.read()

    new_content = expand_doc(content, doc_info.type, config)

    writer = Writer(config)
    final_path = writer.write(target_file, new_content)

    # update config if not already there
    existing_filenames = {f.filename.lower() for f in config.required_files}
    if filename.lower() not in existing_filenames and target_file.lower() not in existing_filenames:
        config.required_files.append(doc_info)
        config_manager.save_config(config)

    state_manager = StateManager(config)
    state_manager.update_doc_state(doc_path=final_path)

    console.print(f"[green]Successfully expanded {target_file}![/green]")

@app.command()
def sync():
    """Syncs existing documentation with current source code state."""
    console.print("[blue]Syncing documentation...[/blue]")
    config_manager = ConfigManager()
    config = config_manager.load_config()

    state_manager = StateManager(config)
    stale_docs = state_manager.get_stale_docs()

    if not stale_docs:
        console.print("[green]All documentation is up to date![/green]")
        return

    console.print(f"[yellow]Found {len(stale_docs)} stale documents. Syncing...[/yellow]")

    parser = Parser(config)
    context = parser.extract_context()
    writer = Writer(config)

    for ds in stale_docs:
        console.print(f"Syncing [cyan]{ds.doc_path}[/cyan]...")

        if not os.path.exists(ds.doc_path):
            console.print(f"[red]Warning: {ds.doc_path} not found. Skipping.[/red]")
            continue

        with open(ds.doc_path, "r", encoding="utf-8") as f:
            current_content = f.read()

        diff = None
        if config.use_git and ds.last_source_hash:
            try:
                base_hash = ds.last_source_hash.split("-dirty-")[0]
                import subprocess
                result = subprocess.run(
                    ["git", "diff", base_hash, "HEAD", "--", ".", ":!documentor.yaml", ":!documentor-lock.yaml"],
                    capture_output=True,
                    text=True,
                    check=False
                )
                if result.returncode == 0:
                    diff = result.stdout
            except Exception:
                pass

        new_content = sync_doc(current_content, context, config, diff)
        final_path = writer.write(ds.doc_path, new_content)

        state_manager.update_doc_state(
            doc_path=final_path,
            tracking_type=ds.tracking_type,
            source_refs=ds.source_refs
        )
        console.print(f"[green]Successfully synced {ds.doc_path}![/green]")

    console.print("[green]Sync complete![/green]")

if __name__ == "__main__":
    app()
