import os
from typing import Optional
import typer
from rich.console import Console
import questionary
from documentor.core.config import ConfigManager
from documentor.llm.chains import generate_docs, edit_doc, expand_doc
from documentor.core.parser import Parser
from documentor.core.writer import Writer

app = typer.Typer(help="Documentor: A CLI tool for automatic documentation generation and management")
console = Console()

def handle_cancel(val):
    if val is None:
        console.print("[red]Initialization cancelled by user.[/red]")
        raise typer.Exit(1)
    return val

@app.command()
def init():
    """Interactive setup to initialize documentor configuration."""
    console.print("[blue]Welcome to Documentor initialization![/blue]")

    config_data = {}

    # choose doc directory
    default_output = handle_cancel(questionary.confirm("Use default output settings (docs directory, no footer)?", default=True).ask())
    if not default_output:
        config_data["docs_dir"] = handle_cancel(questionary.text("Enter output directory for docs:", default="docs").ask())
        config_data["include_footer"] = handle_cancel(questionary.confirm("Include 'Generated by Documentor' footer in markdown?", default=False).ask())

    # analysis/advanced options
    basic_analysis = handle_cancel(questionary.confirm("Use basic analysis system (automatically discovers files to document)?", default=True).ask())
    if basic_analysis:
        config_data["required_only"] = False
        config_data["use_style_md"] = False
    else:
        config_data["required_only"] = True
        config_data["use_style_md"] = handle_cancel(questionary.confirm("Use a style.md file for formatting instructions?", default=True).ask())
        if config_data["use_style_md"]:
            config_data["style_md_path"] = handle_cancel(questionary.text("Enter path to style.md:", default="docs/style.md").ask())

        # required files setup
        setup_required = handle_cancel(questionary.confirm("Do you want to specify required files now? (default is just README.md)", default=False).ask())
        if setup_required:
            required_files = []
            while True:
                filename = handle_cancel(questionary.text("Enter required filename (or empty to finish):", default="").ask())
                if not filename:
                    break
                file_type = handle_cancel(questionary.text(f"Enter document type for {filename}:", default="Overview").ask())
                required_files.append({"filename": filename, "type": file_type})
            if required_files:
                config_data["required_files"] = required_files

    # llm setup
    default_model = handle_cancel(questionary.confirm("Use default model (Google Vertex AI with gemini-3.1-pro)?", default=True).ask())
    if not default_model:
        config_data["provider"] = handle_cancel(questionary.select(
            "Choose LLM provider:",
            choices=["vertexai", "openai", "ollama"],
            default="vertexai"
        ).ask())
        config_data["model"] = handle_cancel(questionary.text("Enter model name:", default="gemini-3.1-pro").ask())

    # file ignores setup
    default_ignore = handle_cancel(questionary.confirm("Use default ignore setup (ignore common dirs like .git, venv, and files > 100KB)?", default=True).ask())
    if not default_ignore:
        size_str = handle_cancel(questionary.text("Ignore files above size (KB):", default="100").ask())
        config_data["ignore_above_size_kb"] = int(size_str) if size_str.isdigit() else 100
        ignore_patterns_str = handle_cancel(questionary.text("Enter ignore patterns (comma-separated):", default=".git, __pycache__, venv, .venv, env, node_modules, .env, *.pyc, *.pyo").ask())
        config_data["ignore_patterns"] = [p.strip() for p in ignore_patterns_str.split(",")]

    # Create config using Pydantic model to handle defaults
    from documentor.core.config import Config
    import yaml

    config = Config(**config_data)

    with open("documentor.yaml", "w", encoding="utf-8") as f:
        yaml.dump(config.model_dump(), f, default_flow_style=False, sort_keys=False)

    console.print("[green]Created documentor.yaml successfully![/green]")

    # Style.md setup
    if getattr(config, "use_style_md", False):
        create_style = handle_cancel(questionary.confirm(f"Do you want to create and initialize {config.style_md_path}?", default=True).ask())
    else:
        create_style = handle_cancel(questionary.confirm("Do you want to create and initialize a style.md file anyway?", default=False).ask())
    if create_style:
        style_path = getattr(config, "style_md_path", "docs/style.md")
        os.makedirs(os.path.dirname(style_path) or ".", exist_ok=True)
        if not os.path.exists(style_path):
            with open(style_path, "w", encoding="utf-8") as f:
                f.write("# Documentation Style Guide\n\nAdd your formatting and style instructions here. These will be used by Documentor when generating your docs.\n")
            console.print(f"[green]Created {style_path}[/green]")
        else:
            console.print(f"[yellow]{style_path} already exists.[/yellow]")

    console.print("[blue]Initialization complete! Run `documentor generate` to generate your documentation.[/blue]")

@app.command()
def generate(target: Optional[str] = typer.Option(None, help="Specific target to generate docs for")):
    """On-demand generation based on documentor.yaml."""
    console.print("[blue]Generating documentation...[/blue]")
    config_manager = ConfigManager()
    config = config_manager.load_config()

    parser = Parser(config)
    context = parser.extract_context(target)

    generate_docs(context, config, target)
    console.print("[green]Generation complete![/green]")

@app.command()
def edit(target_file: str):
    """Iterates on an existing markdown document using AI based on user comments."""
    console.print(f"[blue]Editing {target_file}...[/blue]")
    config_manager = ConfigManager()
    config = config_manager.load_config()

    if not os.path.exists(target_file):
        console.print(f"[red]Error: {target_file} not found.[/red]")
        raise typer.Exit(1)

    comments = typer.prompt("Please enter your comments for the AI")

    with open(target_file, "r", encoding="utf-8") as f:
        content = f.read()

    new_content = edit_doc(content, comments, config)

    writer = Writer(config)
    writer.write(target_file, new_content)
    console.print(f"[green]Successfully edited {target_file}![/green]")

@app.command()
def expand(target_file: str, doc_type: str = typer.Option("functional", "--type", "-t", help="Type of document (functional, decision, etc.)")):
    """Turns scrappy bullet points into a coherent, well-formatted document."""
    console.print(f"[blue]Expanding {target_file}...[/blue]")
    config_manager = ConfigManager()
    config = config_manager.load_config()

    if not os.path.exists(target_file):
        console.print(f"[red]Error: {target_file} not found.[/red]")
        raise typer.Exit(1)

    with open(target_file, "r", encoding="utf-8") as f:
        content = f.read()

    new_content = expand_doc(content, doc_type, config)

    writer = Writer(config)
    writer.write(target_file, new_content)
    console.print(f"[green]Successfully expanded {target_file}![/green]")

if __name__ == "__main__":
    app()
