import os
from documentor.core.config import Config

class Writer:
    def __init__(self, config: Config):
        self.config = config

    def write(self, target_file: str, content: str):
        """Writes markdown content to disk, optionally adding a footer."""

        if self.config.include_footer:
            footer = "\n\n> *Docs generated by [documentor](https://github.com/your-repo/documentor)*" #TODO: update url
            if footer not in content:
                content += footer

        # Ensure directory exists
        target_dir = os.path.dirname(target_file)
        if target_dir:
            os.makedirs(target_dir, exist_ok=True)

        with open(target_file, "w", encoding="utf-8") as f:
            f.write(content)
